### ISSUE TITLE
failed to delete inboxes

### ISSUE THREAD

**Issue by mikestaub** [jackmahoney/emaile2e-javascript-client#2]
I am creating many inboxes in my tests, saving their IDs, then destroying them in a loop at the very end of the test suite. When I do this, all of the DELETE requests fail. Are the inboxes automatically removed after some time?

Here is the response error I am getting so you can check your logs:
```
timestamp":"2018-02-15T01:05:27.487+0000","status":500,"error":"Internal Server Error","message":"No EntityManager with actual transaction available for current thread - cannot reliably process \'remove\' call","path":"/inboxes/3d3be8ed-3cbe-4520-b6e0-29e4da928678
```

**Comment by jackmahoney** [comment]
Thanks @mikestaub . Looks like a Spring error in the backend leaking into the front. I'll write some tests to ensure this functionality is covered. Thanks!
