### ISSUE TITLE
Cannot read property 'type' of undefined at ApiClient.js:297:20

### ISSUE THREAD

**Issue by mbrumagin** [jackmahoney/emaile2e-javascript-client#4]
In your recent versions:
`let payload = await slurp.createRandomInboxUsingPOST(MAILSLURP_API_KEY)`

fails with:
TypeError: Cannot read property 'type' of undefined
      at node_modules/mailslurp-client/src/ApiClient.js:297:20

Due to:
`return this.apiClient.callApi(
        '/inboxes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      )`
vs function definition:
`function callApi(path, httpMethod, pathParams,
      queryParams, collectionQueryParams, headerParams, formParams, bodyParam, authNames, contentTypes, accepts,
      returnType)`

It treats contentTypes (`['application/json']`) as authNames, so it fails. The api call must not have been updated to work with the new function definition?

**Comment by alexandrduduka** [comment]
@jackmahoney, doesn't work for me as well for that same reason, could you give a hand?

**Comment by Dashfire** [comment]
+1

**Comment by jackmahoney** [comment]
Hey sorry everyone, have been away recently, will publish an update for this today. Thanks for pointing it out

**Comment by jackmahoney** [comment]
@mbrumagin, @alexandrduduka  and all, thanks for your patience. I'll be keeping a closer eye on mailslurp going forward, hope to start giving it some more love. Just released an updated build that should fix this. [See new function call](https://github.com/jackmahoney/emaile2e-javascript-client/blob/51ac6c4a8bd4b3834f7647cf3f53cc12f1e9bcbc/src/api/InboxControllerApi.js#L83). Let me know what you use Mailslurp for - it would be nice to know where it is being used. Thanks!

**Comment by ConnectivityChris** [comment]
Hi @jackmahoney, Thanks for the update,

I'm still running into this problem on the most recent version (0.1.1539968052) of the npm package, has it been published with the new api function?
